// Zentraler Skill-Icon-Katalog. Wird vom Generator (parallel) und vom
// Frontend (für die Icon-Auswahl) gelesen.
//
// Jeder Eintrag:
//   key        → Dateiname (skill_<key>.png) und "default:<key>" Sentinel
//   name       → UI-Label (Deutsch)
//   category   → Tab in der Auswahl-Bibliothek
//   subject    → Kern-Beschreibung für den Prompt
//   palette    → Farbpalette-Hinweis für stilistische Konsistenz

const STYLE = (subject, palette) => `A single video game skill icon for an RPG inventory on a fully transparent background.
Style: Stylized MMORPG inventory icon, painterly with soft cel-shading, ${palette} color palette with hints of golden light highlights, clean readable silhouette.
Subject: ${subject}.
Composition: Centered, fills ~80% of the square frame, no border, no text, no UI chrome, no shadow plate beneath. Clear edge silhouette so it reads at small sizes (64px). Crisp edges.
Output: square aspect ratio, transparent background (no checkerboard, no white), high contrast.`;

export const CATALOG = [
  // === HEAL ===
  { key: "heal", name: "Heilung", category: "heal",
    subject: "A glowing green healing potion in a round glass flask with a cork stopper, soft halo of light, a few floating green sparkles, swirling liquid inside",
    palette: "vibrant emerald-green" },
  { key: "heal_medium", name: "Heilung (mittel)", category: "heal",
    subject: "A larger ornate green healing potion in a teardrop-shaped flask with silver trim, glowing brightly with a vortex of green light inside",
    palette: "vibrant emerald-green and silver" },
  { key: "heal_large", name: "Heilung (groß)", category: "heal",
    subject: "A grand golden chalice filled with luminous green elixir, overflowing with healing mist and bright sparkles, gold base with gemstone inlays",
    palette: "vivid green with gold accents" },
  { key: "heal_mega", name: "Mega-Heilung", category: "heal",
    subject: "An ornate crystal vial pulsing with intense green divine light, beams of healing radiance shooting outward, surrounded by a soft holy aura",
    palette: "brilliant emerald-green with golden divine glow" },
  { key: "regen", name: "Regeneration", category: "heal",
    subject: "A single bright green clover leaf with morning dewdrops and glowing sap, magical green particles drifting upward",
    palette: "fresh green and morning gold" },
  { key: "bandage", name: "Verband", category: "heal",
    subject: "A clean white medical bandage roll partly unrolled with a bold red cross symbol, slight magical green shimmer around it",
    palette: "white, red cross, soft green magic" },
  { key: "first_aid", name: "Erste-Hilfe", category: "heal",
    subject: "A white medical first-aid kit box with a bold red cross on top, lid slightly opened revealing a soft green glow inside",
    palette: "white, red, green glow" },
  { key: "heart", name: "Herz", category: "heal",
    subject: "A stylized rounded pink-red heart with a glossy highlight and a glowing white pulse line passing through it",
    palette: "warm pink-red with white accents" },

  // === DAMAGE / OFFENSIVE ===
  { key: "damage_fire", name: "Feuerball", category: "damage",
    subject: "A swirling fireball made of orange and red flames with a bright yellow core, dynamic flame trails curling around it",
    palette: "fiery orange-red with yellow core" },
  { key: "damage_ice", name: "Eissplitter", category: "damage",
    subject: "A sharp jagged ice shard cluster with frosty mist drifting from it, faintly translucent with internal cracks and bluish glow",
    palette: "icy cyan-blue with white highlights" },
  { key: "damage_lightning", name: "Blitz", category: "damage",
    subject: "A jagged electric lightning bolt with a bright white core and yellow electric arcs around it, crackling energy",
    palette: "electric yellow and white-blue" },
  { key: "damage_poison", name: "Gift", category: "damage",
    subject: "A bubbling purple poison vial with a green smoky toxic gas escaping the top, sickly luminous liquid",
    palette: "toxic purple-green with sickly glow" },
  { key: "damage_dagger", name: "Dolch", category: "damage",
    subject: "A sharp curved assassin's dagger with a jeweled hilt and a polished steel blade, slight blood-red glow at the tip",
    palette: "polished steel with crimson and dark leather hilt" },
  { key: "damage_bomb", name: "Bombe", category: "damage",
    subject: "A round black cartoon bomb with a lit yellow-orange fuse, slight smoke trail, glossy round body",
    palette: "deep black with orange spark and warm fuse glow" },
  { key: "damage_skull", name: "Totenkopf", category: "damage",
    subject: "A grinning stylized skull with glowing red eye sockets, slight wisps of dark smoke around it",
    palette: "bone-white with crimson glow and dark smoke" },
  { key: "damage_curse", name: "Fluch", category: "damage",
    subject: "A twisted purple skull surrounded by dark magic runes and swirling purple-black smoke, cursed glow",
    palette: "deep purple and black with magic violet glow" },
  { key: "damage_bleed", name: "Blutung", category: "damage",
    subject: "Three large crimson blood droplets falling with splatter and glistening highlights",
    palette: "deep crimson and dark red" },
  { key: "damage_meteor", name: "Meteor", category: "damage",
    subject: "A fiery meteor rock crashing diagonally with a bright orange flame tail and smoke trail behind it",
    palette: "molten orange with charcoal rock and smoky tail" },

  // === ELEMENTAL ===
  { key: "elem_fire", name: "Feuer-Orb", category: "elemental",
    subject: "A spherical orb of contained swirling flame energy, bright orange-red core with flame wisps escaping",
    palette: "bright fire-orange and red" },
  { key: "elem_water", name: "Wasser-Orb", category: "elemental",
    subject: "A spherical orb of contained churning water with bubbles and droplets, reflective blue surface",
    palette: "deep ocean blue with white foam" },
  { key: "elem_earth", name: "Erde-Orb", category: "elemental",
    subject: "A jagged rock spike emerging from a chunk of brown earth, with small grass tufts and pebbles around it",
    palette: "earthy brown with green grass accents" },
  { key: "elem_wind", name: "Wind-Orb", category: "elemental",
    subject: "A swirling spherical orb of white-blue wind with curving air currents and leaves caught in the gust",
    palette: "pale wind-cyan and white" },
  { key: "elem_lightning", name: "Blitz-Orb", category: "elemental",
    subject: "A spherical orb of contained crackling lightning energy with internal arcs of bright yellow electricity",
    palette: "electric yellow-white with violet edges" },
  { key: "elem_shadow", name: "Schatten-Orb", category: "elemental",
    subject: "A spherical orb of dark purple-black shadow magic with violet wisps escaping, void-like center",
    palette: "deep void purple with violet glow" },
  { key: "elem_light", name: "Licht-Orb", category: "elemental",
    subject: "A spherical orb of pure golden divine light with radiating beams and a soft halo",
    palette: "brilliant white-gold and warm yellow" },
  { key: "elem_arcane", name: "Arkan-Orb", category: "elemental",
    subject: "A spherical orb of swirling magenta-cyan arcane energy with floating runes and sparkles",
    palette: "magenta and cyan with magic sparkles" },

  // === STATUS ===
  { key: "status_freeze", name: "Einfrieren", category: "status",
    subject: "A solid translucent ice cube with frost crystals on it, mist drifting off, cold blue glow",
    palette: "icy cyan and pale blue" },
  { key: "status_burn", name: "Brennen", category: "status",
    subject: "An orange-red flame flickering upward with smoky tendrils, dynamic curling fire",
    palette: "bright orange-red fire" },
  { key: "status_stun", name: "Betäubung", category: "status",
    subject: "Three little bright yellow cartoon stars circling above an empty center, classic dizzy effect",
    palette: "bright cartoon yellow" },
  { key: "status_sleep", name: "Schlaf", category: "status",
    subject: "Three stacked blue cartoon Z letters growing larger upward, sleepy magical sparkles",
    palette: "soft pastel blue and white" },
  { key: "status_silence", name: "Stille", category: "status",
    subject: "A speech bubble with a thick red X stamped over it, muted gray-blue background",
    palette: "muted gray-blue with red X" },
  { key: "status_confuse", name: "Verwirrt", category: "status",
    subject: "Two large purple cartoon question marks tilted and circling each other with a slight magic swirl",
    palette: "vivid purple and pink" },
  { key: "status_root", name: "Wurzeln", category: "status",
    subject: "Dark gnarled roots wrapping upward like vines with small thorns and a moss-green tint",
    palette: "dark brown roots with mossy green" },
  { key: "status_chains", name: "Ketten", category: "status",
    subject: "Heavy iron chain links forming an X shape, slight rusty patina and glinting highlights",
    palette: "dark iron-gray with rust accents" },

  // === BUFFS ===
  { key: "buff_shield", name: "Schild", category: "buff",
    subject: "A polished heater shield with a gold crest of a roaring lion on a blue field, slight magical aura",
    palette: "royal blue and gold with silver edges" },
  { key: "buff_attack", name: "Angriff", category: "buff",
    subject: "Two crossed shining swords with golden hilts and silver blades, a faint red aura behind them",
    palette: "steel silver with gold and crimson aura" },
  { key: "buff_speed", name: "Geschwindigkeit", category: "buff",
    subject: "A pair of winged boots in brown leather with white feathered wings, slight motion-blur trail",
    palette: "warm brown leather with white-gold wings" },
  { key: "buff_strength", name: "Stärke", category: "buff",
    subject: "A clenched muscular fist surrounded by a bright orange power aura, energy emanating outward",
    palette: "rich skin tone with bright orange energy aura" },
  { key: "buff_bless", name: "Segnung", category: "buff",
    subject: "A golden glowing star with radiating divine beams of light, holy aura, small floating golden sparkles",
    palette: "brilliant gold and warm white" },
  { key: "buff_crit", name: "Krit", category: "buff",
    subject: "A red and yellow archery target reticle with a feathered dart hitting the bullseye in the center",
    palette: "bright red and golden yellow" },

  // === DEBUFFS ===
  { key: "debuff_weak", name: "Schwäche", category: "debuff",
    subject: "A cracked broken shield with chips and a long diagonal crack, dull gray with a faint red glow underneath",
    palette: "dull steel-gray with red crack glow" },
  { key: "debuff_slow", name: "Verlangsamung", category: "debuff",
    subject: "A spider web in a hexagonal pattern with a heavy black hourglass in the center",
    palette: "icy white web and dark hourglass" },
  { key: "debuff_doom", name: "Verhängnis", category: "debuff",
    subject: "A black scythe with a curved silver blade dripping with dark purple ooze, ominous purple smoke",
    palette: "black handle, silver blade, deep violet ooze" },
  { key: "debuff_tear", name: "Trauer", category: "debuff",
    subject: "A single large translucent blue teardrop falling with small splash droplets around it, melancholy mood",
    palette: "soft pastel blue with white highlight" },
  { key: "debuff_fear", name: "Furcht", category: "debuff",
    subject: "A purple ghostly skull face with hollow black eyes and a screaming open mouth, purple smoky aura",
    palette: "ghostly purple-violet with black hollows" },

  // === LEVEL / PROGRESSION ===
  { key: "level_up", name: "Level Up", category: "level",
    subject: "A large upward-pointing chunky green arrow with a golden star at the tip, radiating yellow energy lines",
    palette: "vibrant green arrow and golden star" },
  { key: "level_down", name: "Level Down", category: "level",
    subject: "A large downward-pointing chunky red arrow with a sad gray storm cloud behind it",
    palette: "vivid red arrow and somber gray cloud" },
  { key: "level_reset", name: "Reset", category: "level",
    subject: "A bright cyan-blue circular refresh arrow looping around itself, slight motion glow",
    palette: "bright cyan-blue with white motion glow" },
  { key: "trophy", name: "Trophäe", category: "level",
    subject: "A golden trophy cup with two ornate handles, glossy metallic surface and a small star symbol on the front",
    palette: "shiny gold and warm bronze" },
  { key: "crown", name: "Krone", category: "level",
    subject: "A regal golden crown with three large gemstones (ruby red, sapphire blue, emerald green) on the band and ornate spires",
    palette: "rich gold with ruby, sapphire, emerald gems" },

  // === MULTIPLIERS ===
  { key: "mult_x2", name: "×2", category: "multiplier",
    subject: "A big bold chunky 3D number '×2' in glossy bright yellow with red outline, comic-book starburst pattern behind it",
    palette: "comic-book yellow, red, and white starburst" },
  { key: "mult_x3", name: "×3", category: "multiplier",
    subject: "A big bold chunky 3D number '×3' in glossy bright orange with red outline, comic-book starburst pattern behind it",
    palette: "comic-book orange, red, white" },
  { key: "mult_x4", name: "×4", category: "multiplier",
    subject: "A big bold chunky 3D number '×4' in glossy bright red with darker red outline, comic-book starburst behind it",
    palette: "comic-book red and crimson" },
  { key: "mult_x5", name: "×5", category: "multiplier",
    subject: "A big bold chunky 3D number '×5' in glossy purple with golden outline, comic-book starburst behind it",
    palette: "comic-book purple, gold, white" },
  { key: "mult_x10", name: "×10", category: "multiplier",
    subject: "A big bold chunky 3D '×10' in glossy rainbow gradient with golden outline, comic-book starburst pattern, sparkles and rainbow glow",
    palette: "rainbow gradient with gold and white sparkles" },

  // === MISC ===
  { key: "lucky_wheel", name: "Glücksrad", category: "misc",
    subject: "A small carnival-style spinning wheel divided into green and red sectors, gold rim, pointer at top",
    palette: "carnival gold, red, and green" },
  { key: "dice", name: "Würfel", category: "misc",
    subject: "Two playful red gambling dice tumbling at slight angles with white pips and slight motion lines",
    palette: "rich red dice with white pips" },
  { key: "coin", name: "Münze", category: "misc",
    subject: "A glossy gold coin with a star symbol stamped on the front, slight shine highlight on the edge",
    palette: "warm gold and bronze" },
  { key: "gem", name: "Edelstein", category: "misc",
    subject: "A large faceted blue diamond gemstone with multiple shiny facets and bright white sparkles",
    palette: "vivid sapphire blue and white sparkle" },
  { key: "chest", name: "Schatzkiste", category: "misc",
    subject: "A wooden treasure chest with brass trim, lid slightly open revealing a golden glow and floating coins",
    palette: "warm wood-brown, brass-gold, treasure-glow" },
  { key: "key", name: "Schlüssel", category: "misc",
    subject: "An ornate gold skeleton key with a heart-shaped bow and intricate bit, slight magical sparkle",
    palette: "shiny gold with white sparkle" },
  { key: "scroll", name: "Schriftrolle", category: "misc",
    subject: "A magical parchment scroll partly unrolled with glowing arcane runes and a golden wax seal at the top",
    palette: "aged parchment beige and arcane blue glow" },
  { key: "spellbook", name: "Zauberbuch", category: "misc",
    subject: "An ancient leather-bound spellbook with golden filigree and a glowing magical eye on the cover",
    palette: "deep brown leather with golden gilding and arcane purple glow" },
  { key: "crystal_ball", name: "Kristallkugel", category: "misc",
    subject: "A clear crystal sphere on a small bronze stand with swirling purple mystical mist inside",
    palette: "clear crystal with violet mystical mist" },
  { key: "hourglass", name: "Sanduhr", category: "misc",
    subject: "A wooden hourglass with golden sand pouring through the middle, slight magical glow around it",
    palette: "warm wood and golden glowing sand" },
];

export const CATEGORY_LABELS = {
  heal: "Heilung",
  damage: "Schaden",
  elemental: "Elementar",
  status: "Status",
  buff: "Buffs",
  debuff: "Debuffs",
  level: "Level",
  multiplier: "Multiplikator",
  misc: "Sonstiges",
};

export function buildPrompt(entry) {
  return STYLE(entry.subject, entry.palette);
}
